
    create table Calendario (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table Guardarropa (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table Guardarropa_Prenda (
        Guardarropa_id bigint not null,
        prendas_id bigint not null,
        primary key (Guardarropa_id, prendas_id)
    )

    create table Prenda (
        id bigint generated by default as identity (start with 1),
        colorPrimario varchar(255),
        colorSecundario varchar(255),
        nivelAbrigo integer not null,
        tela varchar(255),
        tipo varchar(255),
        usada boolean not null,
        primary key (id)
    )

    create table Sugerencia (
        id bigint generated by default as identity (start with 1),
        estado varchar(255),
        evento_id bigint,
        primary key (id)
    )

    create table Sugerencia_Prenda (
        Sugerencia_id bigint not null,
        atuendo_id bigint not null,
        primary key (Sugerencia_id, atuendo_id)
    )

    create table Usuario (
        id bigint generated by default as identity (start with 1),
        calificaciones varbinary(255),
        maximoDePrendas integer not null,
        tipo integer,
        ultimaSugerencia_id bigint,
        primary key (id)
    )

    create table Usuario_Calendario (
        Usuario_id bigint not null,
        eventos_id bigint not null,
        primary key (Usuario_id, eventos_id)
    )

    create table Usuario_Guardarropa (
        Usuario_id bigint not null,
        guardarropas_id bigint not null,
        primary key (Usuario_id, guardarropas_id)
    )

    create table Usuario_Sugerencia (
        Usuario_id bigint not null,
        sugerencias_id bigint not null,
        primary key (Usuario_id, sugerencias_id)
    )

    alter table Guardarropa_Prenda 
        add constraint UK_8n0axiim561iy41oiei524vwl  unique (prendas_id)

    alter table Usuario_Sugerencia 
        add constraint UK_3vwkt3tneqx3ghmeohm75ifh9  unique (sugerencias_id)

    alter table Guardarropa_Prenda 
        add constraint FK_8n0axiim561iy41oiei524vwl 
        foreign key (prendas_id) 
        references Prenda

    alter table Guardarropa_Prenda 
        add constraint FK_j0c4op9om71xmsy78yoixghjv 
        foreign key (Guardarropa_id) 
        references Guardarropa

    alter table Sugerencia 
        add constraint FK_jpqwgsu9a1iuyvekwncs5lqvv 
        foreign key (evento_id) 
        references Calendario

    alter table Sugerencia_Prenda 
        add constraint FK_rrm6nd08lmt06c0s7eag06x7x 
        foreign key (atuendo_id) 
        references Prenda

    alter table Sugerencia_Prenda 
        add constraint FK_1xm70rphp9yt6y0l3opjpaqw3 
        foreign key (Sugerencia_id) 
        references Sugerencia

    alter table Usuario 
        add constraint FK_fi48dh5vahm7ft72li618vdb7 
        foreign key (ultimaSugerencia_id) 
        references Sugerencia

    alter table Usuario_Calendario 
        add constraint FK_eojoxwfna5knjf0h96nvg1yio 
        foreign key (eventos_id) 
        references Calendario

    alter table Usuario_Calendario 
        add constraint FK_h73nf6y8wknmp9838v188lswc 
        foreign key (Usuario_id) 
        references Usuario

    alter table Usuario_Guardarropa 
        add constraint FK_exvaq4sy1rbjcil7xs13w5xs2 
        foreign key (guardarropas_id) 
        references Guardarropa

    alter table Usuario_Guardarropa 
        add constraint FK_d02fvs98p85p43dex3uu6q7bs 
        foreign key (Usuario_id) 
        references Usuario

    alter table Usuario_Sugerencia 
        add constraint FK_3vwkt3tneqx3ghmeohm75ifh9 
        foreign key (sugerencias_id) 
        references Sugerencia

    alter table Usuario_Sugerencia 
        add constraint FK_gf9xjgqc19miiofw17lp4xbi1 
        foreign key (Usuario_id) 
        references Usuario
