
public enum Material {
		ALGODON, LYCRA, LINO, FRANELA, LANA, CUERO, MICROFIBRA, SEDA,
		JEAN, CHIFFON, SPANDEX, SATEN, LANILLA, POLIESTER, GAMUZA, POLAR, MEZCLILLA,
		NYLON,CAUCHO,MODAL,LONA,RAYON,GABARDINA;
		// Etc.
}
